<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

ERROR - 2017-05-07 18:10:26 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:33:59 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:34:41 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:35:15 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:35:51 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:35:51 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:36:02 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:37:37 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:38:03 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:40:42 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:41:04 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:51:09 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:51:43 --> Could not find the language line "Attribute could not be deleted."
ERROR - 2017-05-07 18:56:39 --> Could not find the language line "Attribute(s) has been added."
ERROR - 2017-05-07 18:56:55 --> Could not find the language line "Category has been updated."
ERROR - 2017-05-07 18:57:03 --> Could not find the language line "Attribute has been deleted."
ERROR - 2017-05-07 18:57:47 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:08:20 --> Query error: Unknown column 'weight' in 'field list' - Invalid query: INSERT INTO `products` (`name`, `slug`, `tags`, `price`, `weight`, `quantity`, `description`, `item_category_id`, `thumb`) VALUES ('a simple product', 'a-simple-product', 'simple, product', '12', '12', '30', 'CodeIgniter gives you access to a Query Builder class. This pattern allows information to be retrieved, inserted, and updated in your database with minimal scripting. In some cases only one or two lines of code are necessary to perform a database action. CodeIgniter does not require that each database table be its own class file. It instead provides a more simplified interface.\r\n\r\nBeyond simplicity, a major benefit to using the Query Builder features is that it allows you to create database independent applications, since the query syntax is generated by each database adapter. It also allows for safer queries, since the values are escaped automatically by the system.', '2', 'assets/images/c68963cbff094aebfa136d48fa4694ce.png')
ERROR - 2017-05-07 19:15:03 --> Query error: Unknown column 'quantity' in 'field list' - Invalid query: INSERT INTO `products` (`name`, `slug`, `tags`, `price`, `weight`, `quantity`, `description`, `item_category_id`, `thumb`) VALUES ('a simple product', 'a-simple-product', 'simple, product', '12', '12', '30', 'CodeIgniter gives you access to a Query Builder class. This pattern allows information to be retrieved, inserted, and updated in your database with minimal scripting. In some cases only one or two lines of code are necessary to perform a database action. CodeIgniter does not require that each database table be its own class file. It instead provides a more simplified interface.\r\n\r\nBeyond simplicity, a major benefit to using the Query Builder features is that it allows you to create database independent applications, since the query syntax is generated by each database adapter. It also allows for safer queries, since the values are escaped automatically by the system.', '2', 'assets/images/620f70cc1655ef598581e89ea3292593.png')
ERROR - 2017-05-07 19:17:20 --> Could not find the language line "Your product has been added."
ERROR - 2017-05-07 19:22:41 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:22:42 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:22:54 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:22:55 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:23:01 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:23:01 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:23:22 --> Could not find the language line "Category has been updated."
ERROR - 2017-05-07 19:28:47 --> Query error: Unknown column 'quantity' in 'field list' - Invalid query: UPDATE `products` SET `name` = 'a simple product', `slug` = 'a-simple-product', `tags` = 'simple, product', `price` = '12.00', `weight` = '12.00', `quantity` = '100', `description` = 'CodeIgniter gives you access to a Query Builder class. This pattern allows information to be retrieved, inserted, and updated in your database with minimal scripting. In some cases only one or two lines of code are necessary to perform a database action. CodeIgniter does not require that each database table be its own class file. It instead provides a more simplified interface.\r\n\r\nBeyond simplicity, a major benefit to using the Query Builder features is that it allows you to create database independent applications, since the query syntax is generated by each database adapter. It also allows for safer queries, since the values are escaped automatically by the system.', `item_category_id` = '2'
WHERE `id` = '1'
ERROR - 2017-05-07 19:29:06 --> Severity: Warning --> Invalid argument supplied for foreach() C:\UwAmp\www\cart\application\models\Product_model.php 469
ERROR - 2017-05-07 19:29:06 --> Could not find the language line "Item has been updated."
ERROR - 2017-05-07 19:30:16 --> Severity: Warning --> Invalid argument supplied for foreach() C:\UwAmp\www\cart\application\models\Product_model.php 469
ERROR - 2017-05-07 19:30:16 --> Could not find the language line "Item has been updated."
ERROR - 2017-05-07 19:49:33 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 19:49:33 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 19:50:26 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 19:50:27 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 19:50:33 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:50:50 --> 404 Page Not Found: Admin/delete_item
ERROR - 2017-05-07 19:50:57 --> 404 Page Not Found: Admin/delete_item
ERROR - 2017-05-07 19:57:11 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:57:21 --> 404 Page Not Found: /index
ERROR - 2017-05-07 19:57:28 --> Severity: Notice --> Undefined property: stdClass::$filename C:\UwAmp\www\cart\application\models\Product_model.php 678
ERROR - 2017-05-07 19:57:28 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:29 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:29 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:30 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:30 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:31 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:31 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:32 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:32 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:33 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:33 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:34 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:35 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:35 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:36 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:36 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:37 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:37 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:38 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:38 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:39 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:40 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:41 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:41 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:42 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:42 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:43 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:43 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:44 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:44 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:45 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:45 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:46 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:46 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:47 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:48 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:48 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:49 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:49 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:50 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:50 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:51 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:56 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:57 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:57 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:58 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:58 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:59 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:57:59 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:00 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:00 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:01 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:01 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:02 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:02 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:03 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:03 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:04 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:05 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:05 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:06 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:07 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:07 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:38 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:38 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:39 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:39 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:40 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:40 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:41 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:41 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:42 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:42 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:43 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:43 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:44 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:45 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:45 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:46 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:46 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:47 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:47 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:48 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:48 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:49 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:49 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:50 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:51 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:51 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:52 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:52 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:53 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:53 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:54 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:54 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:55 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:56 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:56 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:57 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:57 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:58 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:59 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:58:59 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:59:00 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 19:59:00 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:01 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:01 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:02 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:03 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:03 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:04 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:04 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:05 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:05 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:06 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:06 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:07 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:07 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:08 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:08 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:09 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:09 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:10 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:10 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:11 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:00:11 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:31 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:31 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:32 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:32 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:33 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:33 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:34 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:34 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:35 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:36 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:36 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:37 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:38 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:26:38 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:28:44 --> Could not find the language line "Your product has been added."
ERROR - 2017-05-07 20:28:54 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:28:55 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:31:47 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:31:48 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:32:01 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:32:02 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:32:15 --> Severity: Notice --> Undefined property: stdClass::$category C:\UwAmp\www\cart\application\views\admin\products\products_view.php 98
ERROR - 2017-05-07 20:32:15 --> Severity: Notice --> Undefined property: stdClass::$quantity C:\UwAmp\www\cart\application\views\admin\products\products_view.php 99
ERROR - 2017-05-07 20:32:16 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:32:17 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:32:49 --> Severity: Notice --> Undefined property: stdClass::$quantity C:\UwAmp\www\cart\application\views\admin\products\products_view.php 99
ERROR - 2017-05-07 20:32:49 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:32:50 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:33:51 --> Severity: Notice --> Undefined property: stdClass::$quantity C:\UwAmp\www\cart\application\views\admin\products\products_view.php 99
ERROR - 2017-05-07 20:33:51 --> Severity: Notice --> Undefined property: stdClass::$quantity C:\UwAmp\www\cart\application\views\admin\products\products_view.php 99
ERROR - 2017-05-07 20:33:52 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:33:52 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:34:56 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:34:57 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:35:40 --> 404 Page Not Found: /index
ERROR - 2017-05-07 20:38:55 --> Severity: Parsing Error --> syntax error, unexpected ';' C:\UwAmp\www\cart\application\controllers\Admin.php 129
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\controllers\Admin.php 208
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 5
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 13
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 21
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 65
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 86
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 93
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 103
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 112
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 120
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 127
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 137
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 144
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 144
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 146
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 184
ERROR - 2017-05-07 20:41:53 --> Severity: Notice --> Trying to get property of non-object C:\UwAmp\www\cart\application\views\admin\products\product_edit_view.php 245
ERROR - 2017-05-07 20:42:04 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:42:05 --> 404 Page Not Found: Admin/assets
ERROR - 2017-05-07 20:42:09 --> 404 Page Not Found: /index
ERROR - 2017-05-07 20:46:31 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:31 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:32 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:32 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:33 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:33 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:34 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:34 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:35 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:35 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:36 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:36 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:37 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:37 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:38 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:38 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:39 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:39 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:40 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:40 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 20:46:41 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 21:08:25 --> Could not find the language line "Your product has been added."
ERROR - 2017-05-07 21:08:55 --> Could not find the language line "Item(s) was delete."
ERROR - 2017-05-07 21:14:32 --> Could not find the language line "Your product has been added."
ERROR - 2017-05-07 21:25:48 --> Severity: Warning --> Invalid argument supplied for foreach() C:\UwAmp\www\cart\application\models\Product_model.php 469
ERROR - 2017-05-07 21:25:48 --> You did not select a file to upload.
ERROR - 2017-05-07 21:25:48 --> Could not find the language line "Item category has changed, You may want to update attributes"
